/* generated by writeJava methods in Workspace */
package com.Tuuyi.TMPDataModel.generatedClasses.TMPDataModel;

import com.Tuuyi.TDM.*;
import org.apache.log4j.Logger;
import java.util.*;
import java.lang.reflect.Method;
import org.json.*;
import java.util.concurrent.ConcurrentHashMap;

public class ArcPredicateAddlMethods extends ArcPredicate {

  public double value(int i, int j) {
    return 1.0/j; // to be overridden in extension classes - default 
  }
}
