/* generated by writeJava methods in Workspace */
package com.Tuuyi.TMPDataModel.generatedClasses.TMPDataModel;

import com.Tuuyi.TDM.*;
import org.apache.log4j.Logger;
import java.util.*;
import java.lang.reflect.Method;
import org.json.*;
import java.util.concurrent.ConcurrentHashMap;

public class CatalogItem extends  Item {

  protected static final Logger logWriter = Logger.getLogger(CatalogItem.class.getName());
  private static final boolean persistant = false;

  public void inMemoryOnly(boolean local) {inMemoryOnly = local;}
  public boolean getInMemoryOnly() {return inMemoryOnly;}
  public boolean isPersistant() {return persistant;}

  public static boolean isPersistantClass() {return persistant;}

  protected JSONObject rawCatalogData;

  public void setRawCatalogDataRawValueInternal(String rawVal) throws JSONException {
    if (rawVal == null || rawVal.equals("")) {
      rawCatalogData = new JSONObject();
    } else try {
      rawCatalogData = new JSONObject(rawVal);
    } catch (JSONException e) {
      logWriter.error("Error creating JSONObject from raw value " + rawVal + " in " + this);
      throw e;
    }
  }

  public String getRawCatalogDataInternalRawValue() {
    if (rawCatalogData == null) {
      return "{}";
    } else { 
      return (rawCatalogData.toString()).replaceAll("'", "''");
    }
  }

  /** if no arg, assume from db **/
  public CatalogItem() {
    this(true);
  }
  /** if from DB, set nonFunctional slot wrappers to stub **/
  /**    so subsequent slot get will do retrieval         **/
  public CatalogItem(boolean fromDB) {
    super(Workspace.getCurrentWorkspace(), fromDB);
  }
  public CatalogItem(Workspace workspace, boolean fromDB) {
    super(workspace, fromDB);
  }
  public int getId() {
    return id;
  }
  public JSONObject getRawCatalogData() {
    return rawCatalogData;
  }
  public void setId (int a_id) {
      if (a_id> -1) {
        id = a_id;
      }
  }

  public void setRawCatalogData(JSONObject newRawCatalogData) {
    if (newRawCatalogData == null) {
      rawCatalogData = new JSONObject();
    } else { 
      rawCatalogData = newRawCatalogData;
    }
  }

  /* to support remove operation on collections, java objs are equal if id match */
  public boolean equals(Object o) {
    if (!(o instanceof CatalogItem)) //covers o == null case
      return false;
    CatalogItem other = (CatalogItem)o;
    if (this == other)
      return true;
    else
      return other.id == id;
  }

  /* to maintain hashCode contract */
  public int hashCode() {
    if (id == -1) {
      if (isPersistant()) {
        id = Workspace.makeGuid();
      } else {
        id = Workspace.nextId();
      }
    }
    return id;
  }

/** method to marshall data from caching layer object to JSON **/
  public JSONObject asJSON () {
    JSONObject jsonObj = new JSONObject();
    try {
      jsonObj.put("class", "CatalogItem");
      jsonObj.put("id", id);
      jsonObj.put("id", getId());
      if (getRawCatalogData() != null) {
        jsonObj.put("rawCatalogData", getRawCatalogData());
      }
      if (getHasAbstraction() != null) {
        jsonObj.put("hasAbstraction", getHasAbstraction().getId());
      }
      jsonObj.put("id", getId());
      jsonObj.put("score", getScore());
      jsonObj.put("itemId", getItemId());
    } catch (Exception e1) {
      logWriter.error("Error in marshalling to JSON ", e1);
    }
    return jsonObj;
  }


/** method to marshall data from caching layer object to JSON **/
  public JSONObject asJSONTree () {
    ConcurrentHashMap <DomainConcept, DomainConcept> written = new ConcurrentHashMap<DomainConcept, DomainConcept> ();
    return asJSONTreeAux(written);
  }
  public JSONObject asJSONTreeAux (ConcurrentHashMap<DomainConcept, DomainConcept> written) {
    JSONObject jsonObj = new JSONObject();
    try {
      jsonObj.put("class", "CatalogItem");
      jsonObj.put("id", id);
      if (written.contains(this)) {
        return jsonObj;
      }
      written.put(this, this);
      jsonObj.put("id", getId());
      if (getRawCatalogData() != null) {
        jsonObj.put("rawCatalogData", getRawCatalogData());
      }
      if (getHasAbstraction() != null) {
        jsonObj.put("hasAbstraction", getHasAbstraction().asJSONTreeAux(written));
      }
      jsonObj.put("id", getId());
      jsonObj.put("score", getScore());
      jsonObj.put("itemId", getItemId());
      written.remove(this);
    } catch (Exception e1) {
      logWriter.error("Error in marshalling to JSON ", e1);
    }
    return jsonObj;
  }


/** method to update data in caching layer object from JSON **/
  public boolean updateFromJSON (JSONObject jsonObj) {
    try {
      if (!jsonObj.isNull("rawCatalogData")) {
        try {
          rawCatalogData = jsonObj.getJSONObject("rawCatalogData");
        } catch (JSONException je) {
          logWriter.error("Error updating JSONObject slot from JSON object in " + this + ", jsondump: " + jsonObj, je);
        }
      }
      if (!jsonObj.isNull("hasAbstraction")) {
        int hasAbstractionId = jsonObj.optInt("hasAbstraction");
        Abstraction value = AbstractionManager.getInstance().get(hasAbstractionId);
        if(value != null) {
            setHasAbstraction(value);
        }
      }
      if (!jsonObj.isNull("score")) {
        setScore(jsonObj.optDouble("score"));
      }
      if (!jsonObj.isNull("itemId")) {
        setItemId(jsonObj.optString("itemId"));
      }
    } catch (Exception e) {
      logWriter.error("Failure updating from JSON", e);
      return false;
    }
    return true;
  }

}
