/* generated by writeJava methods in Workspace */
package com.Tuuyi.TMPDataModel.generatedClasses.TMPDataModel;

import com.Tuuyi.TDM.*;
import org.apache.log4j.Logger;
import java.util.*;
import java.lang.reflect.Method;
import org.json.*;
import java.util.concurrent.ConcurrentHashMap;

public class PlanAddlMethods extends Plan {

//DL  public Plan(Plan plan) {
//DL    boolean changed;
//DL    this.hasResults = plan.hasResults;
//DL    this.children = new ArrayList<Plan>(0);
//DL    this.cost = plan.cost;
//DL    this.operations = plan.operations;
//DL  }
}
