/* generated by writeJava methods in Workspace */
package com.Tuuyi.TMPDataModel.generatedClasses.TMPDataModel;

import com.Tuuyi.TDM.*;
import org.apache.log4j.Logger;
import java.util.*;
import java.lang.reflect.Method;
import org.json.*;
import java.util.concurrent.ConcurrentHashMap;

public class ScoredTerm extends DomainConcept {

  protected static final Logger logWriter = Logger.getLogger(ScoredTerm.class.getName());
  private static final boolean persistant = false;

  public void inMemoryOnly(boolean local) {inMemoryOnly = local;}
  public boolean getInMemoryOnly() {return inMemoryOnly;}
  public boolean isPersistant() {return persistant;}

  public static boolean isPersistantClass() {return persistant;}

  protected OntologyTerm forTerm = null;

  double score;

  /** if no arg, assume from db **/
  public ScoredTerm() {
    this(true);
  }
  /** if from DB, set nonFunctional slot wrappers to stub **/
  /**    so subsequent slot get will do retrieval         **/
  public ScoredTerm(boolean fromDB) {
    super(Workspace.getCurrentWorkspace(), fromDB);
  }
  public ScoredTerm(Workspace workspace, boolean fromDB) {
    super(workspace, fromDB);
  }
  public int getId() {
    return id;
  }
  public boolean ForTermIsResident() {
      return true;
  }
  public OntologyTerm getForTerm() {

    return forTerm;
  }
  public int getForTermInternalId() {
    if (forTerm == null) {
      return -1;
    } else { 
      return forTerm.getId();
    }
  }
  public double getScore() {
    return score;
  }
  public void setId (int a_id) {
      if (a_id> -1) {
        id = a_id;
      }
  }

  public void setForTerm(OntologyTerm newForTerm) {
    forTerm = newForTerm;
  }
  public void setScore (double a_score) {
    score = a_score;
  }

  /* to support remove operation on collections, java objs are equal if id match */
  public boolean equals(Object o) {
    if (!(o instanceof ScoredTerm)) //covers o == null case
      return false;
    ScoredTerm other = (ScoredTerm)o;
    if (this == other)
      return true;
    else
      return other.id == id;
  }

  /* to maintain hashCode contract */
  public int hashCode() {
    if (id == -1) {
      if (isPersistant()) {
        id = Workspace.makeGuid();
      } else {
        id = Workspace.nextId();
      }
    }
    return id;
  }

/** method to marshall data from caching layer object to JSON **/
  public JSONObject asJSON () {
    JSONObject jsonObj = new JSONObject();
    try {
      jsonObj.put("class", "ScoredTerm");
      jsonObj.put("id", id);
      jsonObj.put("id", getId());
      if (getForTerm() != null) {
        jsonObj.put("forTerm", getForTerm().getId());
      }
      jsonObj.put("score", getScore());
    } catch (Exception e1) {
      logWriter.error("Error in marshalling to JSON ", e1);
    }
    return jsonObj;
  }


/** method to marshall data from caching layer object to JSON **/
  public JSONObject asJSONTree () {
    ConcurrentHashMap <DomainConcept, DomainConcept> written = new ConcurrentHashMap<DomainConcept, DomainConcept> ();
    return asJSONTreeAux(written);
  }
  public JSONObject asJSONTreeAux (ConcurrentHashMap<DomainConcept, DomainConcept> written) {
    JSONObject jsonObj = new JSONObject();
    try {
      jsonObj.put("class", "ScoredTerm");
      jsonObj.put("id", id);
      if (written.contains(this)) {
        return jsonObj;
      }
      written.put(this, this);
      jsonObj.put("id", getId());
      if (getForTerm() != null) {
        jsonObj.put("forTerm", getForTerm().asJSONTreeAux(written));
      }
      jsonObj.put("score", getScore());
      written.remove(this);
    } catch (Exception e1) {
      logWriter.error("Error in marshalling to JSON ", e1);
    }
    return jsonObj;
  }


/** method to update data in caching layer object from JSON **/
  public boolean updateFromJSON (JSONObject jsonObj) {
    try {
      if (!jsonObj.isNull("forTerm")) {
        int forTermId = jsonObj.optInt("forTerm");
        OntologyTerm value = OntologyTermManager.getInstance().get(forTermId);
        if(value != null) {
            setForTerm(value);
        }
      }
      if (!jsonObj.isNull("score")) {
        setScore(jsonObj.optDouble("score"));
      }
    } catch (Exception e) {
      logWriter.error("Failure updating from JSON", e);
      return false;
    }
    return true;
  }


 public ScoredTerm(OntologyTerm term, double score) {
   this.setForTerm(term);
   this.setScore(score);
  }
  
  /**
   * relevance is a combination of term weight, number of local items, and recursive number of items
   * intuition - the higher the weight, the more relevant, the lower the number of items, the more relevant, 
   *    this latter under the assumption we are going to AND results from terms.
   */
  public double relevance() {
    return this.getForTerm().recursiveItemCount > 0 ? this.score / (this.getForTerm().getRecursiveItemCount()+1) : 0;
  }
  
  public String toString() {
    return this.getForTerm().getHasValue();
  }
  
}
